window.__ModuleLoader__.load({
	id: "dsh-plugin-claude-theme",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		/**
		 * Browser half of the Claude theme plugin.
		 *
		 * Build template — `scripts/build.mjs` inlines the plugin id and the token table
		 * from `tokens.mjs` and writes the result to `lib/client.js`. The DSH module
		 * system loads client bundles as factory-registered CJS, so the file is a single
		 * `window.__ModuleLoader__.load({...})` call: running it only registers a
		 * factory, and the body below executes at materialization.
		 */

		/** Identity of this override layer. `overrideTokens` keys layers by source. */
		const PLUGIN_ID = "dsh-plugin-claude-theme";

		/** Complete `--dsw-*` override layer: `{ token: { light, dark } }`. */
		const TOKENS = {
			"--dsw-static-neutral-bluish-50": { light: "#FAF9F5", dark: "#FAF9F5" },
			"--dsw-static-neutral-bluish-60": { light: "#F5F4ED", dark: "#F5F4ED" },
			"--dsw-static-neutral-bluish-75": { light: "#F0EEE6", dark: "#F0EEE6" },
			"--dsw-static-neutral-bluish-100": { light: "#EBE9E0", dark: "#EBE9E0" },
			"--dsw-static-neutral-bluish-150": { light: "#E8E6DC", dark: "#E8E6DC" },
			"--dsw-static-neutral-bluish-200": { light: "#E3E1D7", dark: "#E3E1D7" },
			"--dsw-static-neutral-bluish-300": { light: "#DAD9D4", dark: "#DAD9D4" },
			"--dsw-static-neutral-bluish-400": { light: "#B0AEA5", dark: "#B0AEA5" },
			"--dsw-static-neutral-bluish-500": { light: "#9C9A92", dark: "#9C9A92" },
			"--dsw-static-neutral-bluish-600": { light: "#87867F", dark: "#87867F" },
			"--dsw-static-neutral-bluish-700": { light: "#73726C", dark: "#73726C" },
			"--dsw-static-neutral-bluish-750": { light: "#5E5D59", dark: "#5E5D59" },
			"--dsw-static-neutral-bluish-800": { light: "#3D3D3A", dark: "#3D3D3A" },
			"--dsw-static-neutral-bluish-850": { light: "#2E2D2B", dark: "#2E2D2B" },
			"--dsw-static-neutral-bluish-875": { light: "#262624", dark: "#262624" },
			"--dsw-static-neutral-bluish-900": { light: "#1F1E1D", dark: "#1F1E1D" },
			"--dsw-static-neutral-bluish-950": { light: "#141413", dark: "#141413" },
			"--dsw-static-neutral-bluish-1000": { light: "#0F0E0D", dark: "#0F0E0D" },
			"--dsw-static-neutral-bluish-00": { light: "#FFFFFF", dark: "#FFFFFF" },
			"--dsw-static-neutral-50": { light: "#FAF9F5", dark: "#FAF9F5" },
			"--dsw-static-neutral-100": { light: "#F5F4ED", dark: "#F5F4ED" },
			"--dsw-static-neutral-150": { light: "#F2F0E8", dark: "#F2F0E8" },
			"--dsw-static-neutral-200": { light: "#EBE9E0", dark: "#EBE9E0" },
			"--dsw-static-neutral-250": { light: "#E3E1D7", dark: "#E3E1D7" },
			"--dsw-static-neutral-300": { light: "#DAD9D4", dark: "#DAD9D4" },
			"--dsw-static-neutral-400": { light: "#B0AEA5", dark: "#B0AEA5" },
			"--dsw-static-neutral-500": { light: "#9C9A92", dark: "#9C9A92" },
			"--dsw-static-neutral-550": { light: "#8F8E86", dark: "#8F8E86" },
			"--dsw-static-neutral-600": { light: "#87867F", dark: "#87867F" },
			"--dsw-static-neutral-700": { light: "#55544E", dark: "#55544E" },
			"--dsw-static-neutral-800": { light: "#30302E", dark: "#30302E" },
			"--dsw-static-neutral-850": { light: "#1F1E1D", dark: "#1F1E1D" },
			"--dsw-static-neutral-900": { light: "#141413", dark: "#141413" },
			"--dsw-static-neutral-1000": { light: "#000000", dark: "#000000" },
			"--dsw-static-neutral-00": { light: "#FFFFFF", dark: "#FFFFFF" },
			"--dsw-static-deepseek-50": { light: "#FBF1EC", dark: "#FBF1EC" },
			"--dsw-static-deepseek-100": { light: "#F7E3DA", dark: "#F7E3DA" },
			"--dsw-static-deepseek-200": { light: "#F0CDBD", dark: "#F0CDBD" },
			"--dsw-static-deepseek-300": { light: "#E8B39C", dark: "#E8B39C" },
			"--dsw-static-deepseek-400": { light: "#E0876A", dark: "#E0876A" },
			"--dsw-static-deepseek-450": { light: "#DD8062", dark: "#DD8062" },
			"--dsw-static-deepseek-500": { light: "#D97757", dark: "#D97757" },
			"--dsw-static-deepseek-600": { light: "#C6613F", dark: "#C6613F" },
			"--dsw-static-deepseek-800": { light: "#8A4130", dark: "#8A4130" },
			"--dsw-static-deepseek-900": { light: "#6B3226", dark: "#6B3226" },
			"--dsw-static-deepseek-700-delete": { light: "#B0523A", dark: "#B0523A" },
			"--dsw-static-blue-50": { light: "#FBF1EC", dark: "#FBF1EC" },
			"--dsw-static-blue-75": { light: "#F7E7DE", dark: "#F7E7DE" },
			"--dsw-static-blue-100": { light: "#F2D8CB", dark: "#F2D8CB" },
			"--dsw-static-blue-300": { light: "#E8B39C", dark: "#E8B39C" },
			"--dsw-static-blue-400": { light: "#E0876A", dark: "#E0876A" },
			"--dsw-static-blue-450": { light: "#DD8062", dark: "#DD8062" },
			"--dsw-static-blue-500": { light: "#D97757", dark: "#D97757" },
			"--dsw-static-blue-600": { light: "#C6613F", dark: "#C6613F" },
			"--dsw-static-blue-800": { light: "#8A4130", dark: "#8A4130" },
			"--dsw-static-blue-900": { light: "#6B3226", dark: "#6B3226" },
			"--dsw-static-blue-950": { light: "#3A1F14", dark: "#3A1F14" },
			"--dsw-static-blue-50p": { light: "#FBF1EC", dark: "#FBF1EC" },
			"--dsw-alias-bg-base": { light: "#FAF9F5", dark: "#141413" },
			"--dsw-alias-bg-layer-1": { light: "#FFFFFF", dark: "#30302E" },
			"--dsw-alias-bg-layer-2": { light: "#FFFFFF", dark: "#30302E" },
			"--dsw-alias-bg-layer-3": { light: "#FFFFFF", dark: "#3A3A38" },
			"--dsw-alias-bg-overlay": { light: "#FFFFFF", dark: "#3A3A38" },
			"--dsw-alias-bg-module-platform": { light: "#F5F4ED", dark: "#30302E" },
			"--dsw-alias-bg-multi-select": { light: "#F5F4ED", dark: "#3A3A38" },
			"--dsw-alias-bg-skeleton": { light: "rgba(31, 30, 29, 0.06)", dark: "rgba(222, 220, 209, 0.08)" },
			"--dsw-alias-bg-document-preview": { light: "#E8E6DC", dark: "#1F1E1D" },
			"--dsw-alias-label-document-preview": { light: "#3D3D3A", dark: "#C2C0B6" },
			"--dsw-alias-bg-document-selection": { light: "color-mix(in srgb, #D97757 35%, transparent)", dark: "color-mix(in srgb, #D97757 40%, transparent)" },
			"--dsw-alias-bg-mask-1": { light: "rgba(20, 20, 19, 0.24)", dark: "rgba(0, 0, 0, 0.50)" },
			"--dsw-alias-bg-mask-2": { light: "rgba(20, 20, 19, 0.12)", dark: "rgba(0, 0, 0, 0.20)" },
			"--dsw-alias-bg-mask-3": { light: "rgba(20, 20, 19, 0.48)", dark: "rgba(0, 0, 0, 0.48)" },
			"--dsw-alias-bg-mask-photo": { light: "rgba(20, 20, 19, 0.88)", dark: "rgba(0, 0, 0, 0.88)" },
			"--dsw-alias-bg-mask-drop": { light: "rgba(250, 249, 245, 0.70)", dark: "rgba(48, 48, 46, 0.70)" },
			"--dsw-alias-border-l1": { light: "rgba(31, 30, 29, 0.08)", dark: "rgba(222, 220, 209, 0.08)" },
			"--dsw-alias-border-l2": { light: "rgba(31, 30, 29, 0.16)", dark: "rgba(222, 220, 209, 0.16)" },
			"--dsw-alias-border-l2-darkmode-thin": { light: "rgba(31, 30, 29, 0.16)", dark: "rgba(222, 220, 209, 0.10)" },
			"--dsw-alias-border-l3": { light: "rgba(31, 30, 29, 0.28)", dark: "rgba(222, 220, 209, 0.28)" },
			"--dsw-alias-border-l4": { light: "rgba(31, 30, 29, 0.40)", dark: "rgba(222, 220, 209, 0.40)" },
			"--dsw-alias-border-inverted": { light: "transparent", dark: "rgba(222, 220, 209, 0.10)" },
			"--dsw-alias-border-inverted2": { light: "transparent", dark: "rgba(222, 220, 209, 0.14)" },
			"--dsw-alias-brand-primary": { light: "#C6613F", dark: "#C6613F" },
			"--dsw-alias-brand-primary-invert": { light: "#141413", dark: "#FAF9F5" },
			"--dsw-alias-brand-text": { light: "#141413", dark: "#FAF9F5" },
			"--dsw-alias-brand-primary-new-colorprimary-new-color": { light: "#D97757", dark: "#E0876A" },
			"--dsw-alias-state-business-primary": { light: "#D97757", dark: "#E0876A" },
			"--dsw-alias-state-business-tertiary": { light: "#F7E3DA", dark: "#4A2A20" },
			"--dsw-alias-link": { light: "#C6613F", dark: "#E0876A" },
			"--dsw-alias-label-primary": { light: "#141413", dark: "#FAF9F5" },
			"--dsw-alias-label-primary-dimmed": { light: "#1F1E1D", dark: "#F5F4ED" },
			"--dsw-alias-label-primary-bluish": { light: "#141413", dark: "#FAF9F5" },
			"--dsw-alias-label-primary-foreground": { light: "#FFFFFF", dark: "#FFFFFF" },
			"--dsw-alias-label-primary-inverted": { light: "#FAF9F5", dark: "#30302E" },
			"--dsw-alias-label-secondary": { light: "#3D3D3A", dark: "#C2C0B6" },
			"--dsw-alias-label-tertiary": { light: "#73726C", dark: "#9C9A92" },
			"--dsw-alias-label-caption": { light: "#9C9A92", dark: "#87867F" },
			"--dsw-alias-label-dimmed": { light: "#DEDCD1", dark: "#5E5D59" },
			"--dsw-alias-label-shimmer": { light: "color-mix(in srgb, #141413 30%, transparent)", dark: "color-mix(in srgb, #FAF9F5 45%, transparent)" },
			"--dsw-alias-label-deep-diving": { light: "color-mix(in srgb, #D97757 70%, #4A2A20)", dark: "color-mix(in srgb, #E0876A 55%, #9C9A92)" },
			"--dsw-alias-label-deep-diving-shimmer": { light: "color-mix(in srgb, #D97757 30%, #4A2A20)", dark: "color-mix(in srgb, #E0876A 65%, #D97757)" },
			"--dsw-alias-button-contrast-fill": { light: "#30302E", dark: "#FAF9F5" },
			"--dsw-alias-button-elevated-fill": { light: "#FFFFFF", dark: "#3A3A38" },
			"--dsw-alias-button-floating-fill": { light: "#FFFFFF", dark: "#30302E" },
			"--dsw-alias-button-floating-hover": { light: "#F0EEE6", dark: "#3A3A38" },
			"--dsw-alias-button-ghost-active-border": { light: "#B0AEA5", dark: "#6B6A64" },
			"--dsw-alias-button-ghost-active-fill": { light: "#EBE9E0", dark: "#3A3A38" },
			"--dsw-alias-button-ghost-active-hover": { light: "#F0EEE6", dark: "#45443F" },
			"--dsw-alias-button-info-fill": { light: "#D97757", dark: "#D97757" },
			"--dsw-alias-button-info-hover": { light: "#C6613F", dark: "#E0876A" },
			"--dsw-alias-button-primary-dimmed": { light: "#F0EEE6", dark: "#3A3A38" },
			"--dsw-alias-button-primary-fill": { light: "#C6613F", dark: "#C6613F" },
			"--dsw-alias-button-primary-hover": { light: "#B0523A", dark: "#D97757" },
			"--dsw-alias-button-tool-bar-fill": { light: "rgba(48, 48, 46, 0.50)", dark: "rgba(48, 48, 46, 0.50)" },
			"--dsw-alias-button-tool-bar-fill-invisible": { light: "rgba(31, 31, 31, 0.36)", dark: "rgba(31, 31, 31, 0.36)" },
			"--dsw-alias-button-tool-bar-hover": { light: "rgba(48, 48, 46, 0.60)", dark: "rgba(48, 48, 46, 0.60)" },
			"--dsw-alias-interactive-bg-hover": { light: "rgba(31, 30, 29, 0.05)", dark: "rgba(222, 220, 209, 0.08)" },
			"--dsw-alias-interactive-bg-hover-solid": { light: "#F0EEE6", dark: "#30302E" },
			"--dsw-alias-interactive-bg-hover-accent": { light: "rgba(217, 119, 87, 0.14)", dark: "rgba(224, 135, 106, 0.24)" },
			"--dsw-alias-interactive-bg-hover-danger": { light: "rgba(180, 35, 31, 0.05)", dark: "rgba(232, 140, 130, 0.16)" },
			"--dsw-alias-interactive-bg-active": { light: "rgba(31, 30, 29, 0.10)", dark: "rgba(222, 220, 209, 0.14)" },
			"--dsw-menu-surface-fill": { light: "rgba(250, 249, 245, 0.94)", dark: "rgba(48, 48, 46, 0.45)" },
			"--dsw-alias-menu-group-header-fill": { light: "rgba(250, 249, 245, 0.94)", dark: "rgba(38, 38, 36, 0.94)" },
			"--dsw-specific-menu": { light: "rgba(250, 249, 245, 0.94)", dark: "rgba(38, 38, 36, 0.94)" },
			"--dsw-alias-menu-icon": { light: "#3D3D3A", dark: "#F5F4ED" },
			"--dsw-alias-tooltip-bg": { light: "#262624", dark: "#30302E" },
			"--dsw-alias-tooltip-key-bg": { light: "color-mix(in srgb, #262624, white 18%)", dark: "color-mix(in srgb, #30302E, white 18%)" },
			"--dsw-alias-toast-bg": { light: "#30302E", dark: "#3A3A38" },
			"--dsw-alias-toast-label": { light: "#FAF9F5", dark: "#FAF9F5" },
			"--dsw-alias-switch-thumb": { light: "#FFFFFF", dark: "#9C9A92" },
			"--dsw-alias-turn-trigger-bg": { light: "#F5F4ED", dark: "rgba(222, 220, 209, 0.08)" },
			"--dsw-alias-turn-trigger-bg-hover": { light: "rgba(31, 30, 29, 0.05)", dark: "rgba(222, 220, 209, 0.14)" },
			"--dsw-alias-markdown-code-block": { light: "#F5F4ED", dark: "#1F1E1D" },
			"--dsw-alias-markdown-code-block-banner": { light: "#F0EEE6", dark: "#262624" },
			"--dsw-alias-markdown-code-segment-selected": { light: "#FFFFFF", dark: "#30302E" },
			"--dsw-alias-markdown-code-segment-unselected": { light: "#F5F4ED", dark: "#1F1E1D" },
			"--dsw-alias-markdown-inline-code": { light: "#F0EEE6", dark: "#262624" },
			"--dsw-alias-markdown-citation": { light: "#E8E6DC", dark: "#30302E" },
			"--dsw-alias-markdown-placeholder": { light: "#F5F4ED", dark: "#3A3A38" },
			"--dsw-alias-markdown-tag": { light: "#F0EEE6", dark: "#3A3A38" },
			"--dsw-alias-scrollbar-bg-l1": { light: "#DAD9D4", dark: "#45443F" },
			"--dsw-alias-scrollbar-bg-l2": { light: "#DAD9D4", dark: "#55544E" },
			"--dsw-alias-scrollbar-hover-l1": { light: "#C2C0B6", dark: "#6B6A64" },
			"--dsw-alias-scrollbar-hover-l2": { light: "#C2C0B6", dark: "#6B6A64" },
			"--dsw-alias-state-error-primary": { light: "#B4231F", dark: "#E88C82" },
			"--dsw-alias-state-error-secondary": { light: "#D9534F", dark: "#D9534F" },
			"--dsw-alias-state-success-primary": { light: "#265B19", dark: "#7AB948" },
			"--dsw-alias-state-success-secondary": { light: "#3E9B2E", dark: "#4ED17E" },
			"--dsw-alias-state-success-tertiary": { light: "#E8F3E2", dark: "#22381A" },
			"--dsw-alias-state-warn-primary": { light: "#B26A00", dark: "#E0A03A" },
			"--dsw-alias-state-warn-secondary": { light: "#E0A03A", dark: "#F7AD31" },
			"--dsw-alias-state-warn-tertiary": { light: "#FDF3E0", dark: "#3A2E14" },
			"--dsw-alias-state-warn-label": { light: "#8A5A00", dark: "#E0A03A" },
			"--dsw-alias-state-idle-primary": { light: "#DAD9D4", dark: "#55544E" },
			"--dsw-alias-code-diff-added": { light: "rgba(38, 91, 25, 0.08)", dark: "rgba(122, 185, 72, 0.12)" },
			"--dsw-alias-code-diff-deleted": { light: "rgba(180, 35, 31, 0.08)", dark: "rgba(232, 140, 130, 0.12)" },
			"--dsw-alias-file-diff-added-bg": { light: "#EDF6E7", dark: "#1C2E17" },
			"--dsw-alias-file-diff-added-gutter": { light: "#F5FAF1", dark: "#14230F" },
			"--dsw-alias-file-diff-added-marker": { light: "#3E9B2E", dark: "#7AB948" },
			"--dsw-alias-file-diff-deleted-bg": { light: "#FBEAE7", dark: "#3A1F1C" },
			"--dsw-alias-file-diff-deleted-gutter": { light: "#FDF1EF", dark: "#2A1512" },
			"--dsw-alias-file-diff-deleted-marker": { light: "#B4231F", dark: "#E88C82" },
			"--dsw-specific-bubble": { light: "#F0EEE6", dark: "#30302E" },
			"--dsw-specific-bubble-highlight": { light: "#E8E6DC", dark: "#3A3A38" },
			"--dsw-specific-input-major": { light: "#FFFFFF", dark: "#30302E" },
			"--dsw-specific-login-input": { light: "#F5F4ED", dark: "#1F1E1D" },
			"--dsw-specific-selector": { light: "#F5F4ED", dark: "#30302E" },
			"--dsw-specific-sidebar-fill": { light: "#F5F4ED", dark: "#262624" },
			"--dsw-specific-sidebar-nav-item-active": { light: "#E8E6DC", dark: "#3A3A38" },
			"--dsw-specific-sidebar-nav-item-active-accent": { light: "#F7E3DA", dark: "#4A2A20" },
			"--dsw-specific-sidebar-nav-item-hover": { light: "#F0EEE6", dark: "#30302E" },
			"--dsw-specific-tip": { light: "#F5F4ED", dark: "#30302E" },
			"--dsw-font-markdown-base": { light: "var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-strong": { light: "600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-strong-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-italic": { light: "italic var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "italic var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-italic-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-strong-italic": { light: "italic 600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "italic 600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-base-strong-italic-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h1": { light: "700 calc(21px + var(--dsh-content-font-delta)) / calc(30px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "700 calc(21px + var(--dsh-content-font-delta)) / calc(30px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h1-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h2": { light: "700 calc(19px + var(--dsh-content-font-delta)) / calc(28px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "700 calc(19px + var(--dsh-content-font-delta)) / calc(28px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h2-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h3": { light: "700 calc(18px + var(--dsh-content-font-delta)) / calc(26px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "700 calc(18px + var(--dsh-content-font-delta)) / calc(26px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h3-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h4": { light: "600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "600 var(--dsh-content-font-size,14px) / calc(24px + var(--dsh-content-font-delta)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-h4-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-table": { light: "var(--dsh-content-font-size-secondary,13px)/calc(22px + var(--dsh-content-font-delta-secondary,0px)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dsh-content-font-size-secondary,13px)/calc(22px + var(--dsh-content-font-delta-secondary,0px)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-table-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-table-head": { light: "500 var(--dsh-content-font-size-secondary,13px)/calc(22px + var(--dsh-content-font-delta-secondary,0px)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "500 var(--dsh-content-font-size-secondary,13px)/calc(22px + var(--dsh-content-font-delta-secondary,0px)) var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-table-head-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small": { light: "12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-strong": { light: "600 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "600 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-strong-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-italic": { light: "italic 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "italic 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-italic-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-strong-italic": { light: "italic 600 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "italic 600 12px/20px var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-markdown-small-strong-italic-font-family": { light: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)", dark: "var(--dcl-prose-font, \"Anthropic Serif\", \"Anthropic Serif Variable\", \"Tiempos Text\", \"Tiempos\", ui-serif, Georgia, Cambria, \"Source Serif 4\", \"Songti SC\", SimSun, serif)" },
			"--dsw-font-family": { light: "\"Anthropic Sans\", \"Anthropic Sans Variable\", \"Styrene B\", \"Styrene A\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif", dark: "\"Anthropic Sans\", \"Anthropic Sans Variable\", \"Styrene B\", \"Styrene A\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif" },
			"--dsw-font-family-brand": { light: "\"Anthropic Sans\", \"Anthropic Sans Variable\", \"Styrene B\", \"Styrene A\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif", dark: "\"Anthropic Sans\", \"Anthropic Sans Variable\", \"Styrene B\", \"Styrene A\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif" },
			"--ds-font-family-code": { light: "ui-monospace, \"Anthropic Mono\", \"SF Mono\", SFMono-Regular, Menlo, \"Roboto Mono\", Consolas, \"Liberation Mono\", \"PingFang SC\", \"Microsoft YaHei\", monospace", dark: "ui-monospace, \"Anthropic Mono\", \"SF Mono\", SFMono-Regular, Menlo, \"Roboto Mono\", Consolas, \"Liberation Mono\", \"PingFang SC\", \"Microsoft YaHei\", monospace" },
		};

		/**
		 * Required services. `theme` is provided by `@deepseek-ai/dsh-client-ui-theme`;
		 * declaring it parks this plugin until that provider is live and unloads it if
		 * the provider goes away.
		 */
		const inject = ['theme'];

		/**
		 * Plugin body: stack the Claude token layer over whatever built-in palette the
		 * user selected. Stacking instead of replacing keeps Settings → Appearance
		 * meaningful — light/dark/system still work, and each resolves to Claude's own
		 * light or dark values.
		 * @param ctx - client plugin context.
		 */
		function apply(ctx) {
		  ctx.effect(
		    () => ctx.theme.overrideTokens(PLUGIN_ID, TOKENS),
		    'theme-claude: palette and typography override layer',
		  );
		}

		exports.apply = apply;
		exports.inject = inject;

		return module.exports;
	}
});
